<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<img class="photo image lazy-loading"
    <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
    data-original="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
    src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('itg_LazyLoadingImage::images/Loader.gif') ?>"
    width="<?= /* @escapeNotVerified */ $block->getWidth() ?>"
    height="<?= /* @escapeNotVerified */ $block->getHeight() ?>"
    alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>" />
