<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<span class="product-image-container"
      style="width:<?= /* @escapeNotVerified */ $block->getWidth() ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= /* @escapeNotVerified */ ($block->getRatio() * 100) ?>%;">
        <img class="product-image-photo lazy-loading"
            <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
            data-original="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
            src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('itg_LazyLoadingImage::images/Loader.gif') ?>"
            width="<?= /* @escapeNotVerified */ $block->getResizedImageWidth() ?>"
            height="<?= /* @escapeNotVerified */ $block->getResizedImageHeight() ?>"
            alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>"/></span>
</span>
